name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.0
        env:
          CIBW_BEFORE_ALL: >
            yum install cmake wget -y &&
            bash ./build_tina.sh
          CIBW_BEFORE_BUILD_LINUX: pip install pybind11 && pwd

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
